### ISSUE TITLE
UReplicator installation

### ISSUE THREAD

**Issue by RiseEarly** [uber/uReplicator#15]
We found this project very useful for our use-case. We got through the example 2, with 2 Kafka Clusters [Kafka1 and Kafka2]. But when trying to move the clusters across different servers, we are stuck due to lack of understanding of the right configurations.

When we tried to move the Source Kafka Cluster to a different server, we got the error : "Leader for the Topic[topic_name] is not found". We are not sure if we have configured the system correctly. 

Request to help us proceed here, as we see the UReplicator to be more stable than Apache Mirror Maker and would like to make use of the same in our project.

Thanks.

**Comment by icefury71** [comment]
Can you paste details of your configuration ?

**Comment by ravi45722** [comment]
I started zookeeper as  ./bin/grid start zookeeper
I started kafka2 as        ./bin/grid start kafka2

I modified the SrcKafkaZkPath in uReplicator-Controller/src/main/java/com/uber/stream/kafka/mirrormaker/controller/ControllerStarter.java as 
conf.setSrcKafkaZkPath("172.16.22.12:2181");  where my source cluster (3 nodes cluster. This is one of the zookeeper ip) is running. 

And the config/topicmapping.properties test2 test2 instead of "dummyTopic dummyTopic1"
And also config/consumer.properties      zookeeper.connect=172.16.22.12:2181

and started running the scripts 
./uReplicator-Distribution/target/uReplicator-Distribution-pkg/bin/start-controller-example1.sh
./uReplicator-Distribution/target/uReplicator-Distribution-pkg/bin/start-worker-example1.sh
After i added the topic using 
curl -X POST -d '{"topic":"test2", "numPartitions":"1"}' http://localhost:9000/topics
The error I am getting in the worker is 

kafka.consumer.ConsumerTimeoutException
        at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:69)
        at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:33)
        at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:66)
        at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:58)
        at kafka.mirrormaker.MirrorMakerWorker$MirrorMakerThread.run(MirrorMakerWorker.scala:281)

And the topic is not replicating into destination kafka. Any more configuarations i need to change here?? What I am missing???

**Comment by xhl1988** [comment]
Does zookeeper path need root node?
e.g. conf.setSrcKafkaZkPath("172.16.22.12:2181/cluster1");
config/consumer.properties zookeeper.connect=172.16.22.12:2181/custer1

**Comment by xhl1988** [comment]
@RiseEarly @ravi45722 is the source kafka cluster on other hosts your own cluster? what version is that?

**Comment by icefury71** [comment]
I think this could be because of a version mismatch between workers and the
Kafka brokers. Do you mind summarizing the exact version of all these
components:
* kafka-client version in uReplicator
* Kafka broker version (Source)
* Kafka broker version (Destination)

**Comment by ravi45722** [comment]
By replacing the "org.jacoco" version from "0.7.6-SNAPSHOT" to
"0.7.6.201602180812"
we resolved the zkclient incompatibility

Now we are using
> 0.9.0.0 kafka in both source & dest clusters
> 3.4.6 zookeeper in both source & dest clusters
> 2.10.5 scala in both source & dest clusters
