### ISSUE TITLE
Preserving Partition in the Destination Cluster

### ISSUE THREAD

**Issue by elangoganesan** [uber/uReplicator#4]
Hi All,
This is great work guys in addressing all the short comings of mirror maker . We are trying to see if we can replace this our current setup of mirror with uMirrorMaker before we go live  . We have a strict requirement to preserve ordering of messages in destination cluster to be same as the source cluster . I was going through the code  and looks like there is a message handler support  . Is this the only change we need to do to get it going?

``` scala
 private object defaultMirrorMakerMessageHandler extends MirrorMakerMessageHandler {
    override def handle(record: MessageAndMetadata[Array[Byte], Array[Byte]]): util.List[ProducerRecord[Array[Byte], Array[Byte]]] = {
      // rewrite topic between consuming side and producing side
      val topic = topicMappings.get(record.topic).getOrElse(record.topic)
//Changed to include source partition information
      Collections.singletonList(new ProducerRecord[Array[Byte], Array[Byte]](topic, record.partition(),record.key(), record.message()))
    }
  }
```

Also do you guys have any plans on enabling this as a run time parameter  so that we can override it.

**Comment by xhl1988** [comment]
Hi,

That is the correct change. Meanwhile, you also need to make sure:
1. keep the same number of partitions in source and destination brokers for the same topic.
2. set max.in.flight.requests.per.connection=1. Multiple in flight requests can lose order when previous request is failed.
3. set block.on.buffer.full=true. This is not related to disorder, but this config can prevent data loss since keeping order might impact performance.

However, there might still be some situations which can cause disorder:
1. If one request contains multiple records (even with linger.ms=0, there will still be batching) but acks from broker is lost, then producer will retry and order cannot be preserved. e.g. the result on broker will be like 1,2,3,1,2,3,…. For this situation, one solution is to flush after each record. This can prevent disorder, but will impact performance significantly.
2. If the process is killed before consumer committed latest check-point, when mirrormaker is restarted, it will consume and produce from last check-point which will cause disorder.

**Comment by xhl1988** [comment]
If #partition in src is bigger than #partition in dst temporarily, worker will hash the partition into dst. After you expand in dst, it will go back to 1:1 mapping again.

**Comment by daluu** [comment]
> Also do you guys have any plans on enabling this as a run time parameter so that we can override it.

Is this still a manual code change today? If so, will the question/request ever get on the roadmap? And if not so, what's the needed configuration to enable it today?

Also, I'm interpreting this filed issue to mean preserving the partition key hashing of source cluster messages into the destination. Correct me if I'm wrong.

**Comment by xhl1988** [comment]
@daluu The partition mapping is already supported by adding a file in worker start command with `--dstzk.config dstzk.properties`. The content of that file only need `enable=true`.
Here is the code for the mapping: https://github.com/uber/uReplicator/blob/Federated-uReplicator/uReplicator-Worker/src/main/scala/kafka/mirrormaker/WorkerInstance.scala#L577

For the second part, it's more like preserving the partition number (more restrict than just key).

**Comment by daluu** [comment]
This is only available in federated uReplicator at the moment?
